baseURL = "https://vanted-kiel.de/"
languageCode = "de-DE"
title = "Smartphoniker Sharing | Die klimafreundliche Alternative zum eigenen Camper"
theme = "camper-theme"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = false

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "de"

# Site Params
[params]
logo = "images/logo.svg"
apiURL = "https://camper.osc-fr1.scalingo.io/api/v1"

# meta data
author = "Leon Morten Richter"
description = "Wohnmobil mieten in Kiel und Umgebung. Einfach ✔ Schnell ✔ Günstig ✔ Jetzt online mieten!"

[Languages]
############# 2 - Site en DE
[Languages.de]
weight = 2
languageCode = "de-DE"
#title = "Example site multi-language"
dateFormat = "02.01.2006"

home = "Home"
menufixed = false

footerAboutTitle = "Reisen ist besonders schön, wenn man nicht weiß, wohin es geht. Aber am allerschönsten ist es, wenn man nicht mehr weiß, woher man kommt."
footerQuicklinkTitle = "Quicklinks"
footerDescription = "- Laotse (571 - 531 v. Chr.)"
# footerSubscribeTitle = "Subscribe"

# Hero Area Section
[Languages.de.params.hero]
enable  = true
heading = "Nachhaltig zum Traumcamper"
description = "Du träumst davon, dem Alltag zu entfliehen? Die Seele baumeln und los zu lassen? Spontan unterwegs zu sein oder einfach mal zwei Tage faul am See zu liegen? Diesen Gedanken hatten wir auch! Leider fehlte uns hierzu immer das passende Reisemobil. Eines zu kaufen, damit wir es mit Glück 4-6 Wochen jährlich nutzen können, kam für uns nie in Frage. Wir möchten ihn mit dir und deinen Abenteuern teilen oder ihn für Events als mobiles Büro nutzen. Unser Ziel: Der Camper soll möglichst viele Menschen glücklich machen! Lange stehen mag er nicht."
button  = true
btnText = "Erfahre mehr"
btnURL  = "/about"
videoThumb = "images/slider/header.jpg"
videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.de.params.aboutSm]
enable  = true
title   = "Aufregendes Abenteuer oder entspanntes Wochenende – ganz nach Lust und Laune"
description = "Unser Bus wird im Alltag, von unserem Premium Partner SMARTPHONIKER, als mobiles Büro genutzt. Da er gerne Menschen mag, lässt er sich auch auf dem ein oder anderen Firmenevent blicken. Eine gesunde Work-Life Balance ist wichtig und deswegen bist du gefragt, um unseren Bus die Welt zu zeigen. Tue dir und unserem Smarti etwas Gutes"

# Contact Section
[Languages.de.params.contact]
enable  = true
#topTitle= "DROP US A NOTE"
title   = "Kontaktiere uns."
subtitle= ""
address = "Lise-Meitner-Straße 6, 24223 Schwentinental"
phone   = "0431/ 90700390"
fax     = ""
facebook= "https://www.facebook.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "54.2906368"
mapLongitude= "10.2261235"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.de.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Starte dein Abenteuer!"
subtitle= ""
btnText = "Auf geht's"


# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 4
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 2
[[menu.nav]]
name    = "faqs"
url     = "faq"
weight  = 5
[[menu.nav]]
name    = "booking"
url     = "booking"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "faqs"
url     = "faq"
weight  = 2
[[menu.quicklink]]
name    = "impressum"
url     = "impressum"
weight  = 3
[[menu.quicklink]]
name    = "agb"
url     = "agb"
weight  = 4
[[menu.quicklink]]
name    = "datenschutz"
url     = "datenschutz"
weight  = 5