baseURL = "https://camper.smartphoniker.shop/"
languageCode = "de-DE"
title = "Smartphoniker Sharing | Die klimafreundliche Alternative zum eigenen Camper"
theme = "camper-theme"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "de"

# Site Params
[params]
logo = "images/logo.png"
apiURL = "https://camper.osc-fr1.scalingo.io/api/v1"

# meta data
author = "Leon Morten Richter"
description = "Hier kommt meta rein"

[Languages]
############# 2 - Site en DE
[Languages.de]
weight = 2
languageCode = "de-DE"
#title = "Example site multi-language"
dateFormat = "02.01.2006"

home = "Home"
logo = "images/logo.png"
menufixed = false

footerAboutTitle = "Reisen ist besonders schön, wenn man nicht weiß, wohin es geht. Aber am allerschönsten ist es, wenn man nicht mehr weiß, woher man kommt."
footerQuicklinkTitle = "Quicklinks"
footerDescription = "- Laotse (571 - 531 v. Chr.)"
# footerSubscribeTitle = "Subscribe"

# Hero Area Section
[Languages.de.params.hero]
enable  = true
heading = "Nachhaltig zum Traumcamper"
description = "Du träumst davon, mal aus dem Alltag auszusteigen? Loslassen und die Seele baumeln lassen? Spontan unterwegs sein oder einfach mal 2 Tage faul am See liegen? Diesen Gedanken hatten wir auch, leider fehlte uns hierzu immer das passende Auto. Eines zu kaufen, damit wir es mit Glück 4-6 Woche jährlich nutzen können, kam für uns nie in Frage. Jetzt nutzen wir unseren Bus, um ihn mit dir und deinen Abenteuern zu teilen oder um diesen für Events als mobiles Büro zu nutzen. Unser Ziel: Der Camper soll möglichst viele Menschen glücklich machen! Lange rum stehen mag er nicht."
button  = true
btnText = "Erfahre mehr"
btnURL  = "/about"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.de.params.aboutSm]
enable  = true
title   = "Aufregendes Abenteuer oder entspanntes Wochenende – ganz nach Lust und Laune"
description = "Unser Bus wird im Alltag, von unserem Premium Partner SMARTPHONIKER, als mobiles Büro genutzt. Da er gerne Menschen mag, lässt er sich auch auf dem ein oder anderen Firmenevent blicken. Eine gesunde Work-Life Balance ist wichtig und deswegen bist du gefragt, um unseren Bus die Welt zu zeigen. Tue dir und unserem Smarti etwas Gutes"

# Contact Section
[Languages.de.params.contact]
enable  = true
#topTitle= "DROP US A NOTE"
title   = "Kontaktiere uns."
subtitle= ""
address = "Lise-Meitner-Straße 6, 24223 Schwentinental"
phone   = "0431/ 90700390"
fax     = ""
facebook= "https://www.facebook.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "54.2906368"
mapLongitude= "10.2261235"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.de.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Starte dein Abenteuer!"
subtitle= ""
btnText = "Auf geht's"


# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "faqs"
url     = "about"
weight  = 4
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 5

# Footer Quick links Menu
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "faqs"
url     = "about"
weight  = 2
[[menu.quicklink]]
name    = "impressum"
url     = "about"
weight  = 3
[[menu.quicklink]]
name    = "agb"
url     = "about"
weight  = 4